accepted = [
    "Apache-2.0",
    "MIT",
    "CC0-1.0",
    "PolyForm-Small-Business-1.0.0",
    "ISC",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
    "MPL-2.0",
    "OpenSSL",
]

workarounds = ["ring"]
