---
name: Pre-Commit

on:  # yamllint disable-line rule:truthy
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - name: Install dev dependencies
              run: cargo build --tests
            - uses: pre-commit/action@v3.0.1
